### ISSUE TITLE
Display issues with headers and (on iPhone SE) setup completed screen

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretixscan-ios#12]
I've got some problems with the displayed screens. I use an iPhone SE, but don't know if this appears on other devices, too.

In the settings menu, the "Select event" the first list entry is a bit cut on the upper edge.
![01](https://user-images.githubusercontent.com/22148307/64486588-19d20180-d22f-11e9-9d88-d4fc2eb912b2.jpg)

After updating the list by pulling down, the first list entry's is lined up great, but now the heading suddenly is much bigger.
![02](https://user-images.githubusercontent.com/22148307/64486594-26565a00-d22f-11e9-904f-29195e3cc729.jpg)

This big header appears on the following "select checkin list" screen, too.
![03](https://user-images.githubusercontent.com/22148307/64486646-d6c45e00-d22f-11e9-950b-8f83607f7082.jpg)

On the "setup completed" screen the check mark icon gets cut on the upper and bottom edge. Here, too, I have the big headline.
![04](https://user-images.githubusercontent.com/22148307/64486647-d6c45e00-d22f-11e9-81e1-738fa6de47df.jpg)

Perhaps I'm allone with these optical problems, but I wanted to report it :)

**Comment by raphaelm** [comment]
Thanks! :) We'll look into this. I noticed the scrolling offset and the big headers, too. The cut-off checkbox is probably the trade-off @winsmith made in the last release to prevent the button at the bottom to be cut off. I guess the last issue only appears on iPhone SE which has a pretty small screen compared to other iOS devices.

**Comment by winsmith** [comment]
Hi! Thanks for reporting this. 

- The big headlines are a stylistic choice, so I don't think they count as a bug. Navigation bar titles will be big unless the view below them starts scrolling downwards. This is how Apple is doing it in all their new apps, and this dev is trying to be one of the cool kids. :D~
- Regarding the clipped icon, @raphaelm is correct in assuming that this is the way the view will constrain itself if there is not enough space for the icon. It's not very pretty though, so I'll try to get a PR out that makes that screen a bit nicer on the SE.
- The scroll position bug in your top screenshot is also definitely a bug that I'll check out over the weekend.

**Comment by TimmThaler** [comment]
You're welcome! :) Thank you for creating the app!

I think one problem with the big headers on phones with small screens like the iPhone SE is, that the text is cut off in case it's too long. You can see this at the "Veranstaltung auswählen" (first two screenshots) quite good. The small header is shown completely, the big one is cut off.
What's the visibility on iPhones with bigger screens? Is the (german) text completely visible?
