### ISSUE TITLE
iOS 13.1: displaying issues

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretixscan-ios#13]
Hi there,

I don't know if it's a bug or a feature, but after updating my iPhone to iOS 13 the header background appears no longer white but transparent.

It looks quite nice, although the text, headers and search field are not well readable 😄 

![iOS_13 1_problem](https://user-images.githubusercontent.com/22148307/65817540-98a3d400-e208-11e9-85d1-f044ecefa29a.jpg)

**Comment by raphaelm** [comment]
This is not intended, thank you for letting us know!
