### ISSUE TITLE
Check-in Lists Are Not Handled Correctly in Offline Mode

### ISSUE THREAD

**Issue by BenBals** [pretix/pretixscan-ios#34]
# Set-up description
- We have a number of products. Lets consider two of those: A and B
- We have multiple check-in lists. Let's consider two of them:
   - List 1 is a simple list (i.e., no custom rules) and includes Product A
   - List 2 is a complex list (i.e., custom rules) and includes Product B
       <img width="456" alt="Screenshot 2024-03-29 at 21 10 27" src="https://github.com/pretix/pretixscan-ios/assets/2546622/d8a9e049-1a43-40d5-9df6-8dc097f08030">
- The ticket secrets are signed, not random

# Behaviour
- When scanning on list 1, tickets for product A are rejected, for product B accepted
   -  expected: A accepted, B rejected
     ![product-a-list-1](https://github.com/pretix/pretixscan-ios/assets/2546622/c9096f9e-e372-49b9-a3e8-e65e2dce1f07)
     ![product-b-list-2](https://github.com/pretix/pretixscan-ios/assets/2546622/dc655133-53a3-4ec1-af14-65a54fbbb14b)
- When scanning on list 2, tickets for both products are rejected
  - expected: A rejected, B accepted
  - in both cases, the error is this one
     ![product-a-and-b-list-2](https://github.com/pretix/pretixscan-ios/assets/2546622/0691c9ff-53e3-44d9-b07c-b1ef01a8cb19)

# Version Details
pretixSCAN 1.21.1 on iOS 17.3.1 (21D61)

**Comment by dasGoogle** [comment]
To give @BenBals bug report some more context: 
I also reproduced the issue on my iPad running the same app version as he is. 
When I configure my Android smartphone for the exact same check-in list (on the same event), it works just fine.

**Comment by raphaelm** [comment]
We found the issue, it's a missing "not" in the logic. We'll prepare a fix for the next release!

**Comment by raphaelm** [comment]
Fixed in https://github.com/pretix/pretixscan-ios/commit/17f95bea88f1e8ff607b1072fac5d9a6b6b0225a

**Comment by joelebeau9** [comment]
I have still noticed issues with scanning check-in lists in offline mode. I've added a device with full access but tickets are rejected in offline mode. I've noticed that when looking at the server access logs, the iOS app does not request a list of orders when doing a full sync, whereas the Android app does.
