### ISSUE TITLE
Add option to use device front camera

### ISSUE THREAD

**Issue by fkusei** [pretix/pretixscan-ios#39]
We recently had an internal event where the attendees were asked to check in themselves using some iPads we put up.

Unfortunately it was somewhat difficult for attendees to position their devices behind the iPads for the app to scan correctly. Almost everyone tried to show the QR code to the device front camera first.

It would be incredibly helpful if the front camera could be selected for such occasions.

**Comment by raphaelm** [comment]
This is now possible!
